### ISSUE TITLE
Cleanup Meta Ticket

### ISSUE THREAD

**Issue by armon** [hashicorp/raft#84]
Here are the list of issues, grouped together if they might make sense as a single PR.

State Races
- [x] Raft state should use locks for any fields that are accessed together (e.g. index and term)

Multi-Row Fetching
- [ ] ~~Replace single row lookups with multi row lookups (LogStore / LogCache) (look at cases around log truncation)~~
- [x] Verify the current term has not changed when preparing/processing the AppendEntries message #136

Follower Replication:
- [x] `replicateTo` should verify leadership is current during looping
- [x] Check for any hot loops that do not break on `stopCh`

Change Inflight Tracking
- [x] Remove majorityQuorum
- [x] Inflight tracker should map Node -> Last Commit Index (match index)
- [x] Votes should be ignored from peers that are not part of peer set
- [x] `precommit` may not be necessary with new inflight (likely will be cleaned up via #117)

Improve Membership Tracking
- [x] Peer changes should have separate channel and do not pipeline (we don't want more than one peer change in flight at a time) #117 
- [x] Peers.json should track index and any AddPeer or RemovePeer are ignored from older indexes - #117

Crashes / Restart Issues
- [ ] ~~Panic with old snapshots #85~~
- [ ] ~~TrailingLogs set to 0 with restart bug #86~~

New Tests
- [x] Config change under loss of quorum: #127
- Setup cluster with {A, B, C, D}
- Assume leader is A
- Partition {C, D}
- Remove {B}
- Test should fail to remove B (quorum cannot be reached)

/cc: @superfell @ongardie @sean- @ryanuber @slackpad

**Comment by ongardie** [comment]
Thanks for writing that up, @armon. I'll take a shot at "Change inflight tracking".

**Comment by ongardie** [comment]
I'll start on 'precommit may not be necessary with new inflight' (though I only have about 20min right now, ugh).

**Comment by slackpad** [comment]
Ok I'm going to go ahead and merge #117. Here's the list of remaining tasks I identified from that. Most of these are already marked inline with TODO comments:

* [ ] Fixup `NewRaft()` to understand legacy `LogAddPeer` and `LogRemovePeer` entries
* [ ] Work through live upgrade scenario now that we have a new config format and ignore old config messages (will we need to support the legacy `LogAddPeer` and `LogRemovePeer` to make the transition work?)
* [ ] Clean up observer interface to use new types (we could probably just use the new server structure here)
* [ ] Add staging -> voter promotion logic
* [ ] Implement `GetConfiguration()`
* [ ] Resolve `quorumSize()`
* [ ] Resolve "barf on new address"
* [ ] Resolve "leaving r.getLastLog() in the wrong state"
* [ ] Resolve "take the req in as a single argument"
* [ ] Resolve broken unit tests
* [ ] Add tests for new peer transitions
* [ ] Add old-format snapshot test
* [ ] Resolve "what is this" in `replicate()`
* [ ] Resolve in `updateLastAppended()`

**Comment by slackpad** [comment]
@ongardie got one trivial PR up #127 and will be sweeping through the unit tests tomorrow fixing the integration tests as well as the commented out ones.

**Comment by ongardie** [comment]
Cool, thanks @slackpad. I've got a busy day tomorrow but can help out later in the week.

**Comment by slackpad** [comment]
Cool I will keep adding the unit test work to the same PR in that case.

**Comment by slackpad** [comment]
Ok I think #127 is in good shape for merge. Tomorrow I'm going to spend some time on these two items:

>  Work through live upgrade scenario now that we have a new config format and ignore old config messages (will we need to support the legacy LogAddPeer and LogRemovePeer to make the transition work?)
> We need a mechanism for manual peer updates after an outage - there's currently no equivalent of "editing peers.json" so it doesn't seem possible to recover from all outage scenarios; there's one broken test related to this as well: TestRaft_SnapshotRestore_PeerChange

Will experiment a little and write up a spec so we can figure out the right way forward with these. We will need a way for Consul to take the existing peers.json and call some new Raft APIs in order to start up the cluster as well, since the peers.json had the only state related to the peers if a snapshot had been taken. I don't think I want to reintroduce the peer store into Raft, but Consul will need to parse this file outside of Raft and call some bootstrap-y thing to get going. I think this problem is closely related to the items above.

**Comment by ongardie-sfdc** [comment]
@slackpad, small request: could you number the post-117 checklist above? It'd help me track things.

**Comment by slackpad** [comment]
@ongardie numbered the todo list

**Comment by ongardie-sfdc** [comment]
BTW I'm trying to refactor a ton of stuff that'll help or fix the following:
* "5 - Add staging -> voter promotion logic"
* "16 - Resolve "what is this" in replicate()"
* "17 - Resolve in updateLastAppended()"
* "19 - Think through the possibility of having two replication threads going to the same peer - see these comments for details"

so save those for me for now :)

**Comment by slackpad** [comment]
@ongardie thanks for the heads up. I'm working on 1, 2, 3 which should not conflict with your stuff too much. Should have a PR up soon so you can see what I'm thinking wrt. to these. Have a good weekend!

**Comment by ongardie-sfdc** [comment]
@slackpad, now that I know you don't have too much outstanding, can we move `runFSM` out to `fsm.go` and `runSnapshots`, `shouldSnapshot`, `takeSnapshot` out to `snapshot.go`? See where I'm going with this? Every goroutine that has its own independent state goes in a different file. Later on, they get kicked off of the Raft struct so that they're not reaching into things they shouldn't.

**Comment by slackpad** [comment]
Yep - I was starting to think about that, too. I'll go ahead and make that change and commit it now so we have a good basis for further work.

**Comment by slackpad** [comment]
@ongardie the split is done under https://github.com/hashicorp/raft/pull/135 - went ahead and merged it.

**Comment by ongardie-sfdc** [comment]
Thanks @slackpad!

**Comment by ongardie-sfdc** [comment]
Some bookkeeping:

* In the top checklist, "Verify the current term has not changed when preparing/processing the AppendEntries message" will be resolved by #136 (please annotate).
* In the post-117 checklist, (9 quorumSize), (16 replicate), (17 updateLastAppended) will be resolved by #136 (please annotate).
* New: Update or delete `membership.md` now that the work happened.
* New: Add a note to `type configurations` that `latest` and `committed` may be the same, and often are.
* In the post-117 checklist, expand (11 getLastLog) to panic any time the stores fail and we're not sure what ought to happen.

I think that's all I'm sitting on.

**Comment by slackpad** [comment]
@ongardie-sfdc thanks for the update and the detailed reviews! I reconciled all your changes with the checklists (added new numbered items for the two new ones).

**Comment by slackpad** [comment]
After merging the version and recovery stuff into issue-84-integration, I cut https://github.com/hashicorp/raft/tree/library-v2-stage-one. I'll integrate and ship the next version of Consul against this branch and keep it open for small fixes I can pick from here if needed. This'll free up the issue-84-integration branch for the goroutine changes and a possible period of instability as that settles in.

After giving the community a heads up wrt. the interface changes we can take issue-84-integration into master.

**Comment by superfell** [comment]
Am seeing some issues with AddPeer after last nights merge, Is there a test somewhere that adds a new peer to a cluster, I did a scan though but didn't spot one for that. @ongardie @slackpad

**Comment by slackpad** [comment]
Hi @superfell - there's a test here that hits it - https://github.com/hashicorp/raft/blob/issue-84-integration/raft_test.go#L2217-L2258. It's likely that you are calling `AddPeer()` but haven't set the `ProtcolVersion` back via configuration to a version that supports it - if you set it to `1` things should work as before.

**Comment by slackpad** [comment]
Also, if you don't need to support any of the old stuff, I'd keep the `ProtocolVersion` at 3 and swap out your `AddPeer()` call with a call to `AddVoter()`.

**Comment by superfell** [comment]
Ahh, the setting of protocolVer in DefaultConfig() was messing with me.

**Comment by slackpad** [comment]
Yeah now that we have backwards compatibility maybe we should default that to `1` and make people opt in to the new stuff - that's probably a little nicer initial experience.

**Comment by slackpad** [comment]
Everything is done or tracked elsewhere - closing!
